[package]
name = "runner"
version = "0.1.0"
authors = ["Noah Callaway <noah@apsis.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
ctrlc = { version = "3.1.3", features = ["termination"]}